# fly.toml app configuration file generated for whalesongs on 2024-12-19T00:10:44-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whalesongs'
primary_region = 'den'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

